# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PoC1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 331, 151))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(140, 80, 181, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 100, 181, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 120, 181, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 60, 181, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 40, 181, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 20, 181, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 150, 331, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(140, 40, 41, 22))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(120, 40, 21, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(190, 40, 21, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(210, 40, 41, 22))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(260, 40, 21, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(280, 40, 41, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(260, 20, 61, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_28.setGeometry(QtCore.QRect(140, 60, 181, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(120, 80, 21, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(190, 80, 21, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(280, 80, 41, 22))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(260, 80, 21, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_30.setGeometry(QtCore.QRect(140, 80, 41, 22))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(210, 80, 41, 22))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(140, 110, 71, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(120, 130, 21, 16))
        self.label_38.setObjectName("label_38")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_32.setEnabled(False)
        self.lineEdit_32.setGeometry(QtCore.QRect(140, 130, 41, 22))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_33.setEnabled(False)
        self.lineEdit_33.setGeometry(QtCore.QRect(280, 130, 41, 22))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(190, 130, 21, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(260, 130, 21, 16))
        self.label_40.setObjectName("label_40")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_34.setEnabled(False)
        self.lineEdit_34.setGeometry(QtCore.QRect(210, 130, 41, 22))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(340, 270, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 290, 95, 20))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 310, 331, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_41 = QtWidgets.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_3)
        self.label_43.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_47.setObjectName("label_47")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_35.setEnabled(False)
        self.lineEdit_35.setGeometry(QtCore.QRect(140, 80, 41, 22))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(140, 100, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(140, 120, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(140, 20, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 140, 181, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(190, 100, 93, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 120, 93, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(10, 490, 121, 16))
        self.label_48.setObjectName("label_48")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(140, 490, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 490, 93, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 560, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 26))
        self.menubar.setObjectName("menubar")
        self.menuSoKa = QtWidgets.QMenu(self.menubar)
        self.menuSoKa.setObjectName("menuSoKa")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSoKa.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Artikel Stammdaten"))
        self.label.setText(_translate("MainWindow", "Artikelnummer"))
        self.label_2.setText(_translate("MainWindow", "Bezeichnung"))
        self.label_3.setText(_translate("MainWindow", "Zeichnungsnummer"))
        self.label_4.setText(_translate("MainWindow", "Referenzkundennummer"))
        self.label_5.setText(_translate("MainWindow", "Referenzkunde"))
        self.label_6.setText(_translate("MainWindow", "Referenznummer"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Körper"))
        self.label_25.setText(_translate("MainWindow", "Hüllkörper [mm]"))
        self.label_26.setText(_translate("MainWindow", "Materialbezeichnung"))
        self.label_27.setText(_translate("MainWindow", "Aufmaß [mm]"))
        self.label_28.setText(_translate("MainWindow", "Querschnitt"))
        self.label_29.setText(_translate("MainWindow", "a"))
        self.label_30.setText(_translate("MainWindow", "b"))
        self.label_31.setText(_translate("MainWindow", "c"))
        self.label_32.setText(_translate("MainWindow", "Länge"))
        self.label_33.setText(_translate("MainWindow", "a"))
        self.label_34.setText(_translate("MainWindow", "b"))
        self.label_35.setText(_translate("MainWindow", "c"))
        self.label_36.setText(_translate("MainWindow", "Abmessungen"))
        self.label_37.setText(_translate("MainWindow", "Halbzeug"))
        self.label_38.setText(_translate("MainWindow", "a"))
        self.label_39.setText(_translate("MainWindow", "b"))
        self.label_40.setText(_translate("MainWindow", "c"))
        self.radioButton.setText(_translate("MainWindow", "Stange"))
        self.radioButton_2.setText(_translate("MainWindow", "Zuschnitt"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Bearbeitung"))
        self.label_41.setText(_translate("MainWindow", "Maschine"))
        self.label_42.setText(_translate("MainWindow", "Aufspannungen"))
        self.label_43.setText(_translate("MainWindow", "Planfräsen"))
        self.label_44.setText(_translate("MainWindow", "Konturfräsen"))
        self.label_45.setText(_translate("MainWindow", "Bohrungen"))
        self.label_46.setText(_translate("MainWindow", "Taschen"))
        self.label_47.setText(_translate("MainWindow", "Vergütung"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Maschine 4712"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ramsdorfer Maschine"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Köln-Kalk Verbot"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "lorem ipsum"))
        self.pushButton.setText(_translate("MainWindow", "Definieren"))
        self.pushButton_2.setText(_translate("MainWindow", "Definieren"))
        self.label_48.setText(_translate("MainWindow", "Mengenstaffelung"))
        self.pushButton_3.setText(_translate("MainWindow", "Definieren"))
        self.pushButton_4.setText(_translate("MainWindow", "Kalkulieren"))
        self.menuSoKa.setTitle(_translate("MainWindow", "SoKa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

