# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PoC.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_materialmaster = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_materialmaster.setGeometry(QtCore.QRect(10, 10, 481, 161))
        self.groupBox_materialmaster.setObjectName("groupBox_materialmaster")
        self.label_articleName = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_articleName.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.label_articleName.setObjectName("label_articleName")
        self.label_referenceID = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_referenceID.setGeometry(QtCore.QRect(10, 130, 171, 16))
        self.label_referenceID.setObjectName("label_referenceID")
        self.label_referenceCustomerID = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_referenceCustomerID.setGeometry(QtCore.QRect(10, 90, 171, 16))
        self.label_referenceCustomerID.setObjectName("label_referenceCustomerID")
        self.label_referenceCustomer = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_referenceCustomer.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.label_referenceCustomer.setObjectName("label_referenceCustomer")
        self.label_articleID = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_articleID.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label_articleID.setObjectName("label_articleID")
        self.label_sketchID = QtWidgets.QLabel(self.groupBox_materialmaster)
        self.label_sketchID.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.label_sketchID.setObjectName("label_sketchID")
        self.lineEdit_articleID = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_articleID.setGeometry(QtCore.QRect(170, 30, 301, 22))
        self.lineEdit_articleID.setObjectName("lineEdit_articleID")
        self.lineEdit_articleName = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_articleName.setGeometry(QtCore.QRect(170, 50, 301, 22))
        self.lineEdit_articleName.setObjectName("lineEdit_articleName")
        self.lineEdit_sketchID = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_sketchID.setGeometry(QtCore.QRect(170, 70, 301, 22))
        self.lineEdit_sketchID.setObjectName("lineEdit_sketchID")
        self.lineEdit_referenceCustomerID = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_referenceCustomerID.setGeometry(QtCore.QRect(170, 90, 301, 22))
        self.lineEdit_referenceCustomerID.setObjectName("lineEdit_referenceCustomerID")
        self.lineEdit_referenceCustomer = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_referenceCustomer.setGeometry(QtCore.QRect(170, 110, 301, 22))
        self.lineEdit_referenceCustomer.setObjectName("lineEdit_referenceCustomer")
        self.lineEdit_referenceID = QtWidgets.QLineEdit(self.groupBox_materialmaster)
        self.lineEdit_referenceID.setGeometry(QtCore.QRect(170, 130, 301, 22))
        self.lineEdit_referenceID.setObjectName("lineEdit_referenceID")
        self.groupBox_body = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_body.setGeometry(QtCore.QRect(10, 170, 481, 141))
        self.groupBox_body.setObjectName("groupBox_body")
        self.label_material = QtWidgets.QLabel(self.groupBox_body)
        self.label_material.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_material.setObjectName("label_material")
        self.label_crosssection = QtWidgets.QLabel(self.groupBox_body)
        self.label_crosssection.setGeometry(QtCore.QRect(150, 40, 171, 16))
        self.label_crosssection.setObjectName("label_crosssection")
        self.label_length = QtWidgets.QLabel(self.groupBox_body)
        self.label_length.setGeometry(QtCore.QRect(330, 40, 171, 16))
        self.label_length.setObjectName("label_length")
        self.label_body = QtWidgets.QLabel(self.groupBox_body)
        self.label_body.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.label_body.setObjectName("label_body")
        self.label_allowance = QtWidgets.QLabel(self.groupBox_body)
        self.label_allowance.setGeometry(QtCore.QRect(10, 80, 171, 16))
        self.label_allowance.setObjectName("label_allowance")
        self.label_semifinished = QtWidgets.QLabel(self.groupBox_body)
        self.label_semifinished.setGeometry(QtCore.QRect(10, 100, 171, 16))
        self.label_semifinished.setObjectName("label_semifinished")
        self.label_bodySideA = QtWidgets.QLabel(self.groupBox_body)
        self.label_bodySideA.setGeometry(QtCore.QRect(160, 60, 16, 16))
        self.label_bodySideA.setObjectName("label_bodySideA")
        self.label_bodySideB = QtWidgets.QLabel(self.groupBox_body)
        self.label_bodySideB.setGeometry(QtCore.QRect(240, 60, 16, 16))
        self.label_bodySideB.setObjectName("label_bodySideB")
        self.label_bodySideC = QtWidgets.QLabel(self.groupBox_body)
        self.label_bodySideC.setGeometry(QtCore.QRect(340, 60, 16, 16))
        self.label_bodySideC.setObjectName("label_bodySideC")
        self.label_allowanceSideA = QtWidgets.QLabel(self.groupBox_body)
        self.label_allowanceSideA.setGeometry(QtCore.QRect(160, 80, 16, 16))
        self.label_allowanceSideA.setObjectName("label_allowanceSideA")
        self.label_allowanceSideB = QtWidgets.QLabel(self.groupBox_body)
        self.label_allowanceSideB.setGeometry(QtCore.QRect(240, 80, 16, 16))
        self.label_allowanceSideB.setObjectName("label_allowanceSideB")
        self.label_allowanceSideC = QtWidgets.QLabel(self.groupBox_body)
        self.label_allowanceSideC.setGeometry(QtCore.QRect(340, 80, 16, 16))
        self.label_allowanceSideC.setObjectName("label_allowanceSideC")
        self.label_semifinishedSideB = QtWidgets.QLabel(self.groupBox_body)
        self.label_semifinishedSideB.setGeometry(QtCore.QRect(240, 100, 16, 16))
        self.label_semifinishedSideB.setObjectName("label_semifinishedSideB")
        self.label_semifinishedSideA = QtWidgets.QLabel(self.groupBox_body)
        self.label_semifinishedSideA.setGeometry(QtCore.QRect(160, 100, 16, 16))
        self.label_semifinishedSideA.setObjectName("label_semifinishedSideA")
        self.label_semifinishedSideC = QtWidgets.QLabel(self.groupBox_body)
        self.label_semifinishedSideC.setGeometry(QtCore.QRect(340, 100, 16, 16))
        self.label_semifinishedSideC.setObjectName("label_semifinishedSideC")
        self.lineEdit_material = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_material.setGeometry(QtCore.QRect(170, 20, 301, 22))
        self.lineEdit_material.setObjectName("lineEdit_material")
        self.lineEdit_bodySideA = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_bodySideA.setGeometry(QtCore.QRect(170, 60, 61, 22))
        self.lineEdit_bodySideA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bodySideA.setObjectName("lineEdit_bodySideA")
        self.lineEdit_bodySideB = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_bodySideB.setGeometry(QtCore.QRect(250, 60, 61, 22))
        self.lineEdit_bodySideB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bodySideB.setObjectName("lineEdit_bodySideB")
        self.lineEdit_bodySideC = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_bodySideC.setGeometry(QtCore.QRect(350, 60, 61, 22))
        self.lineEdit_bodySideC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bodySideC.setObjectName("lineEdit_bodySideC")
        self.lineEdit_allowanceSideA = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_allowanceSideA.setGeometry(QtCore.QRect(170, 80, 61, 22))
        self.lineEdit_allowanceSideA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_allowanceSideA.setObjectName("lineEdit_allowanceSideA")
        self.lineEdit_allowanceSideB = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_allowanceSideB.setGeometry(QtCore.QRect(250, 80, 61, 22))
        self.lineEdit_allowanceSideB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_allowanceSideB.setObjectName("lineEdit_allowanceSideB")
        self.lineEdit_allowanceSideC = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_allowanceSideC.setGeometry(QtCore.QRect(350, 80, 61, 22))
        self.lineEdit_allowanceSideC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_allowanceSideC.setObjectName("lineEdit_allowanceSideC")
        self.lineEdit_semifinishedSideA = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_semifinishedSideA.setEnabled(False)
        self.lineEdit_semifinishedSideA.setGeometry(QtCore.QRect(170, 100, 61, 22))
        self.lineEdit_semifinishedSideA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_semifinishedSideA.setObjectName("lineEdit_semifinishedSideA")
        self.lineEdit_semifinishedSideB = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_semifinishedSideB.setEnabled(False)
        self.lineEdit_semifinishedSideB.setGeometry(QtCore.QRect(250, 100, 61, 22))
        self.lineEdit_semifinishedSideB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_semifinishedSideB.setObjectName("lineEdit_semifinishedSideB")
        self.lineEdit_semifinishedSideC = QtWidgets.QLineEdit(self.groupBox_body)
        self.lineEdit_semifinishedSideC.setEnabled(False)
        self.lineEdit_semifinishedSideC.setGeometry(QtCore.QRect(350, 100, 61, 22))
        self.lineEdit_semifinishedSideC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_semifinishedSideC.setObjectName("lineEdit_semifinishedSideC")
        self.groupBox_modification = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_modification.setGeometry(QtCore.QRect(10, 310, 481, 201))
        self.groupBox_modification.setObjectName("groupBox_modification")
        self.label_machine = QtWidgets.QLabel(self.groupBox_modification)
        self.label_machine.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label_machine.setObjectName("label_machine")
        self.label_stretching = QtWidgets.QLabel(self.groupBox_modification)
        self.label_stretching.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.label_stretching.setObjectName("label_stretching")
        self.label_faceMilling = QtWidgets.QLabel(self.groupBox_modification)
        self.label_faceMilling.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.label_faceMilling.setObjectName("label_faceMilling")
        self.label_contourMilling = QtWidgets.QLabel(self.groupBox_modification)
        self.label_contourMilling.setGeometry(QtCore.QRect(10, 90, 171, 16))
        self.label_contourMilling.setObjectName("label_contourMilling")
        self.label_drilling = QtWidgets.QLabel(self.groupBox_modification)
        self.label_drilling.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.label_drilling.setObjectName("label_drilling")
        self.label_pockets = QtWidgets.QLabel(self.groupBox_modification)
        self.label_pockets.setGeometry(QtCore.QRect(10, 130, 171, 16))
        self.label_pockets.setObjectName("label_pockets")
        self.label_aging = QtWidgets.QLabel(self.groupBox_modification)
        self.label_aging.setGeometry(QtCore.QRect(10, 150, 171, 16))
        self.label_aging.setObjectName("label_aging")
        self.label_volumeScaling = QtWidgets.QLabel(self.groupBox_modification)
        self.label_volumeScaling.setGeometry(QtCore.QRect(10, 170, 171, 16))
        self.label_volumeScaling.setObjectName("label_volumeScaling")
        self.lineEdit_stretching = QtWidgets.QLineEdit(self.groupBox_modification)
        self.lineEdit_stretching.setGeometry(QtCore.QRect(170, 50, 61, 22))
        self.lineEdit_stretching.setObjectName("lineEdit_stretching")
        self.lineEdit_drilling = QtWidgets.QLineEdit(self.groupBox_modification)
        self.lineEdit_drilling.setEnabled(False)
        self.lineEdit_drilling.setGeometry(QtCore.QRect(170, 110, 61, 22))
        self.lineEdit_drilling.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_drilling.setObjectName("lineEdit_drilling")
        self.lineEdit_pockets = QtWidgets.QLineEdit(self.groupBox_modification)
        self.lineEdit_pockets.setEnabled(False)
        self.lineEdit_pockets.setGeometry(QtCore.QRect(170, 130, 61, 22))
        self.lineEdit_pockets.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pockets.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pockets.setObjectName("lineEdit_pockets")
        self.lineEdit_volumeScaling = QtWidgets.QLineEdit(self.groupBox_modification)
        self.lineEdit_volumeScaling.setEnabled(False)
        self.lineEdit_volumeScaling.setGeometry(QtCore.QRect(170, 170, 61, 22))
        self.lineEdit_volumeScaling.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_volumeScaling.setObjectName("lineEdit_volumeScaling")
        self.comboBox_machine = QtWidgets.QComboBox(self.groupBox_modification)
        self.comboBox_machine.setGeometry(QtCore.QRect(170, 30, 301, 22))
        self.comboBox_machine.setObjectName("comboBox_machine")
        self.comboBox_machine.addItem("")
        self.comboBox_machine.addItem("")
        self.comboBox_machine.addItem("")
        self.comboBox_aging = QtWidgets.QComboBox(self.groupBox_modification)
        self.comboBox_aging.setGeometry(QtCore.QRect(170, 150, 301, 22))
        self.comboBox_aging.setObjectName("comboBox_aging")
        self.comboBox_aging.addItem("")
        self.comboBox_aging.addItem("")
        self.pushButton_drilling = QtWidgets.QPushButton(self.groupBox_modification)
        self.pushButton_drilling.setGeometry(QtCore.QRect(240, 110, 93, 22))
        self.pushButton_drilling.setObjectName("pushButton_drilling")
        self.pushButton_pockets = QtWidgets.QPushButton(self.groupBox_modification)
        self.pushButton_pockets.setGeometry(QtCore.QRect(240, 130, 93, 22))
        self.pushButton_pockets.setObjectName("pushButton_pockets")
        self.pushButton_volumeScaling = QtWidgets.QPushButton(self.groupBox_modification)
        self.pushButton_volumeScaling.setGeometry(QtCore.QRect(240, 170, 93, 22))
        self.pushButton_volumeScaling.setObjectName("pushButton_volumeScaling")
        self.radioButton_bar = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_bar.setGeometry(QtCore.QRect(500, 260, 95, 20))
        self.radioButton_bar.setChecked(True)
        self.radioButton_bar.setObjectName("radioButton_bar")
        self.radioButton_cutted = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cutted.setGeometry(QtCore.QRect(500, 280, 95, 20))
        self.radioButton_cutted.setObjectName("radioButton_cutted")
        self.pushButton_calculation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculation.setGeometry(QtCore.QRect(670, 530, 93, 28))
        self.pushButton_calculation.setObjectName("pushButton_calculation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SoKa"))
        self.groupBox_materialmaster.setTitle(_translate("MainWindow", "Artikelstammdaten"))
        self.label_articleName.setText(_translate("MainWindow", "Bezeichnung"))
        self.label_referenceID.setText(_translate("MainWindow", "Referenznummer"))
        self.label_referenceCustomerID.setText(_translate("MainWindow", "Referenzkundennummer"))
        self.label_referenceCustomer.setText(_translate("MainWindow", "Referenzkunde"))
        self.label_articleID.setText(_translate("MainWindow", "Artikelnummer"))
        self.label_sketchID.setText(_translate("MainWindow", "Zeichnungsnummer"))
        self.groupBox_body.setTitle(_translate("MainWindow", "Körper"))
        self.label_material.setText(_translate("MainWindow", "Materialbezeichnung"))
        self.label_crosssection.setText(_translate("MainWindow", "Querschnitt"))
        self.label_length.setText(_translate("MainWindow", "Länge"))
        self.label_body.setText(_translate("MainWindow", "Hüllkörper [mm]"))
        self.label_allowance.setText(_translate("MainWindow", "Aufmaß [mm]"))
        self.label_semifinished.setText(_translate("MainWindow", "Halbzeug [mm]"))
        self.label_bodySideA.setText(_translate("MainWindow", "a"))
        self.label_bodySideB.setText(_translate("MainWindow", "b"))
        self.label_bodySideC.setText(_translate("MainWindow", "c"))
        self.label_allowanceSideA.setText(_translate("MainWindow", "a"))
        self.label_allowanceSideB.setText(_translate("MainWindow", "b"))
        self.label_allowanceSideC.setText(_translate("MainWindow", "c"))
        self.label_semifinishedSideB.setText(_translate("MainWindow", "b"))
        self.label_semifinishedSideA.setText(_translate("MainWindow", "a"))
        self.label_semifinishedSideC.setText(_translate("MainWindow", "c"))
        self.lineEdit_bodySideA.setText(_translate("MainWindow", "10"))
        self.lineEdit_bodySideB.setText(_translate("MainWindow", "15"))
        self.lineEdit_bodySideC.setText(_translate("MainWindow", "20"))
        self.lineEdit_allowanceSideA.setText(_translate("MainWindow", "5"))
        self.lineEdit_allowanceSideB.setText(_translate("MainWindow", "0"))
        self.lineEdit_allowanceSideC.setText(_translate("MainWindow", "5"))
        self.lineEdit_semifinishedSideA.setText(_translate("MainWindow", "20"))
        self.lineEdit_semifinishedSideB.setText(_translate("MainWindow", "20"))
        self.lineEdit_semifinishedSideC.setText(_translate("MainWindow", "30"))
        self.groupBox_modification.setTitle(_translate("MainWindow", "Bearbeitung"))
        self.label_machine.setText(_translate("MainWindow", "Maschine"))
        self.label_stretching.setText(_translate("MainWindow", "Aufspannungen"))
        self.label_faceMilling.setText(_translate("MainWindow", "Planfräsen"))
        self.label_contourMilling.setText(_translate("MainWindow", "Konturfräsen"))
        self.label_drilling.setText(_translate("MainWindow", "Bohrungen"))
        self.label_pockets.setText(_translate("MainWindow", "Taschen"))
        self.label_aging.setText(_translate("MainWindow", "Vergütung"))
        self.label_volumeScaling.setText(_translate("MainWindow", "Mengenstaffelung"))
        self.lineEdit_drilling.setText(_translate("MainWindow", "0"))
        self.lineEdit_pockets.setText(_translate("MainWindow", "0"))
        self.lineEdit_volumeScaling.setText(_translate("MainWindow", "0"))
        self.comboBox_machine.setItemText(0, _translate("MainWindow", "Maschine 4711"))
        self.comboBox_machine.setItemText(1, _translate("MainWindow", "Ramsdorfer Kölsch"))
        self.comboBox_machine.setItemText(2, _translate("MainWindow", "Köln-Kalk Verbot"))
        self.comboBox_aging.setItemText(0, _translate("MainWindow", "Test Entry 1"))
        self.comboBox_aging.setItemText(1, _translate("MainWindow", "Test Entry 2"))
        self.pushButton_drilling.setText(_translate("MainWindow", "Definieren"))
        self.pushButton_pockets.setText(_translate("MainWindow", "Definieren"))
        self.pushButton_volumeScaling.setText(_translate("MainWindow", "Definieren"))
        self.radioButton_bar.setText(_translate("MainWindow", "Stange"))
        self.radioButton_cutted.setText(_translate("MainWindow", "Zuschnitt"))
        self.pushButton_calculation.setText(_translate("MainWindow", "Kalkulieren"))

